### PR TITLE
Albert fixes

### PR DESCRIPTION
**Pull request by jthoward64**

### CODE REVIEW

**Comment by jthoward64** [comment]
Currently giving me a weird error about iTunes verions, seems to still think rustpush is windows

**Comment by jthoward64** [comment]
Branch is tested and working (at least for sending messages). This PR is pretty similar to #5 except that this one add a parameter for the serial number rather than hardcoding it

**Review by TaeHagen — CHANGES_REQUESTED** [review]
Please keep formatting and code changes separate, as it makes it hard to tell what actually changed. Thank you for your contribution!

**Comment by jthoward64** [comment]
Apologies, that will have been my autoformatter, 66962dc should undo everything not related to the fixes

**Comment by TaeHagen** [comment]
Thank you!

**Pull request merged**
